### ISSUE TITLE
Error can not read collection

### ISSUE THREAD

**Issue by timmit147** [M4TThys123/Blok-Tech-Team#49]
Ik krijg deze error de eersten keer dat ik de server start en wanneer ik opnieuw de server start is die weg. Ik denk dat de code van marloes is maar ik weet het niet zeker?

![image](https://user-images.githubusercontent.com/29665951/111996743-9d55f980-8b1a-11eb-8b66-acdeb6441b19.png)

**Comment by marloestacx** [comment]
Volgensmij krijg je dit omdat je te snel naar de pagina gaat en er nog geen verbinding is gemaakt met de database
