### ISSUE TITLE
Stijling footer mischien met zelften iconen als design

### ISSUE THREAD

**Issue by timmit147** [M4TThys123/Blok-Tech-Team#50]
Mischien de footer nog het zelfden maken als het design. De kleur misschien wit maken van chat berichten?

![image](https://user-images.githubusercontent.com/29665951/111997235-1ead8c00-8b1b-11eb-96c3-01f794881b64.png)

![image](https://user-images.githubusercontent.com/29665951/111997460-574d6580-8b1b-11eb-81be-a83b65920295.png)

**Comment by ROEL2407** [comment]
icons (versturen en camera) veranderen naar font awesome en footer van vragen adden veranderen
